### ISSUE TITLE
Blizzy's toolbar button icon is purple

### ISSUE THREAD

**Issue by brustmopf** [henrybauer/AutoAsparagus#4]
Hi,

I'm running into an issue using asparagus with blizzy's toolbar.

The asparagus icon is purple. Can this be that the texture apth is incorrect ? Do you have the same issue ?

If I'm the only one having this very visible issue I'll try to fix it myself and post the solution code. If you have it as well let's try to solve it together.

Cheers

**Comment by henrybauer** [comment]
I can reproduce it.

![purple](https://user-images.githubusercontent.com/5103358/39715192-239f73ee-5235-11e8-89a7-ed0ec7fbaf3d.png)

**Comment by henrybauer** [comment]
Fixed in newest version
